### ISSUE TITLE
npm run build error work arounds

### ISSUE THREAD

**Issue by lae0901** [leocll/vscode-extension-webview-template#7]
getting error when I run "npm run build".   NPM seems to have a problem with the braces used for output grouping
```
      "buildweb": "pushd ./web &> /dev/null && { npm run build; popd &> /dev/null; }",
```
so I replaced with a bash shell script named ./scripts/buildweb.sh
```
#!/usr/bin/env bash

pushd ./web &> /dev/null 
npm run build
popd &> /dev/null
  
```

and run it from npm 
```
        "buildweb": "sh ./scripts/buildweb.sh",
```

**Comment by leocll** [comment]
`pushd` is a `bash` command, `dash` does not support `pushd` command, you should be developing on `linux`, the built-in sh of `linux` defaults to `dash`, You can modify like this
```
"buildweb": "cd ./web && { npm run build; cd -;}",
```
Second, there should be no spaces before `}`
